branch-defaults:
  default:
    environment: photography-portfolio-env
    group_suffix: null
environment-defaults:
  photography-portfolio-env:
    branch: null
    repository: null
global:
  application_name: photography_portfolio
  branch: null
  default_ec2_keyname: Tanay_DevOps_Project_KeyPair
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application